# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and Deploy Python Project to Azure Function App - Ai-Model-Purchase
 
on:
  push:
    branches:
      - main
  workflow_dispatch:
 
env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'Procurementportal' # Set to correct function directory
  PYTHON_VERSION: '3.10' # Python runtime version
 
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
 
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
 
      - name: Install dependencies
        run: pip install -r procurementportal/requirements.txt
 
      # Optional: Add step to run tests here
 
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download repository for deployment
        uses: actions/checkout@v4
 
      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'Ai-Model-Purchase'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_68322386CD1442F085811A4A0B7D9097 }}
 
      - name: Restart Function App (Ensuring Sync)
        run: |
          az functionapp restart --name Ai-Model-Purchase --resource-group AIModel-Dev-RG
